apiRules:
- exclude:
    uidRegex: ^System\.Object$
- exclude:
    uidRegex: ^System\.ValueType$
# - exclude:
    # uidRegex: ^System\.Attribute$
    # type: Type
- include:
    uidRegex: '^System\.[^.]*Exception$'
    type: Type
- include:
    uidRegex: ^Discord\.Addons\.MpGame\.[^.]*Attribute$
    type: Type
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.MpGameModuleBase`1$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.MpGameModuleBase`2$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.MpGameService`1$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.IMpGameServiceConfig$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.ILogStrings$