apiRules:
- exclude:
    uidRegex: ^System\.Object$
- exclude:
    uidRegex: ^System\.ValueType
- include:
    uidRegex: '^System\.[^.]*Exception$'
    type: Type
- exclude:
    # CLL Node
    uidRegex: ^Discord\.Addons\.MpGame\.Collections\.Node`1$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.Collections\.Pile`1\.DefaultWrapper$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.Collections\.Pile`2\.Wrap$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.MpGameModuleBase`1$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.MpGameModuleBase`2$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.MpGameService`1$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.IMpGameServiceConfig$
- exclude:
    uidRegex: ^Discord\.Addons\.MpGame\.ILogStrings$