### YamlMime:ManagedReference
items:
- uid: Discord.Addons.MpGame.IMpGameServiceConfig
  commentId: T:Discord.Addons.MpGame.IMpGameServiceConfig
  id: IMpGameServiceConfig
  parent: Discord.Addons.MpGame
  children:
  - Discord.Addons.MpGame.IMpGameServiceConfig.LogStrings
  langs:
  - csharp
  - vb
  name: IMpGameServiceConfig
  nameWithType: IMpGameServiceConfig
  fullName: Discord.Addons.MpGame.IMpGameServiceConfig
  type: Interface
  source:
    remote:
      path: src/Discord.Addons.MpGame/Services/Config/IMpGameServiceConfig.cs
      branch: master
      repo: git@github.com:Joe4evr/Discord.Addons.git
    id: IMpGameServiceConfig
    path: ../src/Discord.Addons.MpGame/Services/Config/IMpGameServiceConfig.cs
    startLine: 4
  assemblies:
  - Discord.Addons.MpGame
  namespace: Discord.Addons.MpGame
  syntax:
    content: public interface IMpGameServiceConfig
    content.vb: Public Interface IMpGameServiceConfig
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Discord.Addons.MpGame.IMpGameServiceConfig.LogStrings
  commentId: P:Discord.Addons.MpGame.IMpGameServiceConfig.LogStrings
  id: LogStrings
  parent: Discord.Addons.MpGame.IMpGameServiceConfig
  langs:
  - csharp
  - vb
  name: LogStrings
  nameWithType: IMpGameServiceConfig.LogStrings
  fullName: Discord.Addons.MpGame.IMpGameServiceConfig.LogStrings
  type: Property
  source:
    remote:
      path: src/Discord.Addons.MpGame/Services/Config/IMpGameServiceConfig.cs
      branch: master
      repo: git@github.com:Joe4evr/Discord.Addons.git
    id: LogStrings
    path: ../src/Discord.Addons.MpGame/Services/Config/IMpGameServiceConfig.cs
    startLine: 8
  assemblies:
  - Discord.Addons.MpGame
  namespace: Discord.Addons.MpGame
  syntax:
    content: ILogStrings LogStrings { get; }
    parameters: []
    return:
      type: Discord.Addons.MpGame.ILogStrings
    content.vb: ReadOnly Property LogStrings As ILogStrings
  overload: Discord.Addons.MpGame.IMpGameServiceConfig.LogStrings*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Discord.Addons.MpGame
  commentId: N:Discord.Addons.MpGame
  isExternal: false
  name: Discord.Addons.MpGame
  nameWithType: Discord.Addons.MpGame
  fullName: Discord.Addons.MpGame
- uid: Discord.Addons.MpGame.IMpGameServiceConfig.LogStrings*
  commentId: Overload:Discord.Addons.MpGame.IMpGameServiceConfig.LogStrings
  isExternal: false
  name: LogStrings
  nameWithType: IMpGameServiceConfig.LogStrings
  fullName: Discord.Addons.MpGame.IMpGameServiceConfig.LogStrings
- uid: Discord.Addons.MpGame.ILogStrings
  commentId: T:Discord.Addons.MpGame.ILogStrings
  parent: Discord.Addons.MpGame
  isExternal: false
  name: ILogStrings
  nameWithType: ILogStrings
  fullName: Discord.Addons.MpGame.ILogStrings
